# Generated by Django 5.0.1 on 2025-04-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcepcionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('disponible', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Excepción de Horario',
                'verbose_name_plural': 'Excepciones de Horarios',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_turno', models.IntegerField(default=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Horario',
                'verbose_name_plural': 'Configuraciones de Horarios',
                'unique_together': {('dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
