# Generated by Django 5.0.1 on 2025-05-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diasdisponibles',
            options={'ordering': ['fecha'], 'verbose_name': 'Día disponible', 'verbose_name_plural': 'Días disponibles'},
        ),
        migrations.AddField(
            model_name='diasdisponibles',
            name='motivo',
            field=models.CharField(blank=True, help_text='Motivo por el cual el día no está disponible', max_length=255, null=True),
        ),
    ]
